[package]
name = "politeia-core"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
serde.workspace = true
schemars.workspace = true
thiserror.workspace = true
uuid.workspace = true
jiff.workspace = true
blake3.workspace = true
serde_json.workspace = true

