fn main() -> anyhow::Result<()> {
    let arg = std::env::args().nth(1).unwrap_or_else(|| "help".into());
    match arg.as_str() {
        "derive" => {
            std::fs::create_dir_all("generated")?;
            std::fs::write("generated/README.md", "# Generated projections\n\nGenerated by `cargo run -p xtask -- derive`.\n")?;
            println!("derived starter projections");
        }
        "check" => {
            for required in [
                "docs/02-CONSTITUTION.md",
                "docs/03-ONTOLOGY.md",
                "docs/04-KERNEL_CONTRACT.md",
                "docs/18-FIRST_VERTICAL_SLICE.md",
            ] {
                anyhow::ensure!(std::path::Path::new(required).exists(), "missing {required}");
            }
            println!("starter structural checks passed");
        }
        _ => println!("usage: cargo run -p xtask -- [derive|check]"),
    }
    Ok(())
}
